---

forgejo_database:
  db_type: sqlite3
  charset: utf8
  path: /var/lib/forgejo/data/forgejo.db
  log_sql: false

forgejo_repository:
  root: /var/lib/forgejo/data/forgejo-repositories

forgejo_server:
  domain: forgejo.molecule.lan
  protocol: http
  http_addr: "127.0.0.1"
  http_port: 3000
  root_url: https://forgejo.molecule.lan
  disable_ssh: true
  # ssh_domain: forgejo.molecule.lan
  landing_page: login
  lfs_start_server: false
  # lfs_jwt_secret: OkAglKI7wKkBlT1l5YyncFM-vyDpQbEZefzQKcaoVxE

forgejo_git:
  home_path: /var/lib/forgejo/data/home

forgejo_lfs:
  path: /var/lib/forgejo/data/lfs

forgejo_mailer:
  enabled: false

forgejo_service:
  register_email_confirm: false

forgejo_openid:
  enable_openid_signin: false
  enable_openid_signup: false

forgejo_log:
  mode: console
  level: info
  root_path: /var/lib/forgejo/log
  # router: console

forgejo_security:
  install_lock: true
  internal_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2ODEyMjMxMjR9.tTmy5Nuv6_p66VZCxASiviwKSZCFk9GXggQ1-naqH7g

forgejo_admin_user:
  username: "root"
  password: "{{ vault__forgejo.root }}"
  email: "root@example.com"

forgejo_auths:
  ldap:
    state: "present"
    name: "ldap"
    active: true
    security_protocol: "Unencrypted"
    # skip_tls_verify: ""
    hostname: "auth"
    port: "389"
    user_search_base: "dc=molecule,dc=lan"
    filters:
      # (&(objectClass=posixAccount)(|(uid=%[1]s)(mail=%[1]s)))
      user: "(cn=%s)"
      admin: "ou=admins,ou=groups,dc=molecule,dc=lan"
      restricted: "ou=forgejo,ou=groups,dc=molecule,dc=lan"
    attributes:
      username: "cn"
      firstname: "givenName"
      sur name: "sn"
      email: "email"
    bind_dn: "cn=admin,dc=molecule,dc=lan"
    bind_password: "{{ vault__ldap.admin }}"
    synchronize_users: true

...
