---

forgejo_config_dir: /etc/forgejo
forgejo_working_dir: /var/lib/forgejo

forgejo_runner_controller:
  hostname: "forgejo"
  remoteuser: "forgejo"
  username: "forgejo"

forgejo_runner_register:
    # "{{ (ansible_facts | default({})) | bodsch.core.hostname(inventory_hostname=ansible_facts['hostname']) }}"
  - name: "{{ ansible_facts.hostname }}"
    tags: []
    instance: "http://forgejo.molecule.lan:3000"
    secret: "4ef3eb262c04aad5e279511c1c86f7377e28d6b9"
    scope: ""
    labels:
      - ubuntu-latest
      - ubuntu-22.04

forgejo_runner_config:
  log:                                                  #
    level: warn                                         # trace, debug, info, warn, error, fatal
  runner:                                               #
    file: .runner
    capacity: 2
    envs:
      MOLECULE_DOCKER_HOST: tcp://molecule.matrix.lan:2376
    env_file: .env
    timeout: 3h
    insecure: true
    fetch_timeout: 5s
    fetch_interval: 2s
    labels:
      - label: self-hosted
        type: host
        container: "-self-hosted"
      # - label: ubuntu-latest
      #   type: docker
      #   container: catthehacker/ubuntu:act-latest

...
