---
repos:
  - repo: local
    hooks:
      - id: flake8-local
        name: flake8 (lokal)
        entry: bash -c 'flake8 --append-config=.config/flake8.cfg'
        language: system
        types: [python]
        # exclude: |
        #   ^(\.git|\.venv|env|venv|build|dist|__pycache__)/
        # args: [--max-line-length=150]

      - id: pycodestyle-custom
        name: pycodestyle (custom)
        entry: bash -c 'pycodestyle plugins/ --config=.config/pycodestyle.cfg --statistics --count --exclude=test_*.py --exclude=hooks/*.py'
        language: system
        types: [python]
