namespace: bodsch
name: scm

version: 1.8.0

readme: README.md

authors:
  - Bodo Schulz <bodo@boone-schulz.de>

description: Collection of Ansible modules to communicate with SCM systems.

license_file: 'LICENSE'

tags:
  - scm
  - git
  - github
  - forgejo

dependencies:
  "community.general": "*"
  "bodsch.core": ">=2.9.0"

repository: https://github.com/bodsch/ansible-collection-scm
documentation: https://github.com/bodsch/ansible-collection-scm/README.md
homepage: https://github.com/bodsch/ansible-collection-scm
issues: https://github.com/bodsch/ansible-collection-scm/issues

build_ignore:
  - "galaxy.yml"
  - "*.pyc"
  - "*.retry"
  - ".ansible-lint"
  - ".editorconfig"
  - ".flake8"
  - ".gitignore"
  - ".yamllint"
  - ".github"
