---

- name: create admin user
  when:
    - not running_in_check_mode
    - (forgejo_admin_user.username is defined and forgejo_admin_user.username | string | length > 0)
    - (forgejo_admin_user.password is defined and forgejo_admin_user.password | string | length > 0)
    - (forgejo_admin_user.email is defined and forgejo_admin_user.email | string | length > 0)
  remote_user: "{{ forgejo_remote_user }}"
  become_user: "{{ forgejo_system_user }}"
  become: true
  bodsch.scm.forgejo_admin_user:
    username: "{{ forgejo_admin_user.username }}"
    password: "{{ forgejo_admin_user.password }}"
    email: "{{ forgejo_admin_user.email }}"
    config: "{{ forgejo_config_dir }}/forgejo.ini"
    working_dir: "{{ forgejo_working_dir }}"

- name: validate user passwords
  when:
    - not running_in_check_mode
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.set_fact:
    forgejo_validated_passwords: "{{ forgejo_users | bodsch.scm.validate_passwords(forgejo_security) }}"

- name: password states
  when:
    - not running_in_check_mode
    - forgejo_validated_passwords.failed
  ansible.builtin.fail:
    msg: "your users passwords are not valid!\n
         {{ forgejo_validated_passwords.result | to_nice_yaml }}"
  run_once: true

- name: create local users
  when:
    - not running_in_check_mode
    - forgejo_users | default([]) | count > 0
  bodsch.scm.forgejo_users:
    users: "{{ forgejo_users | default([]) }}"
    api_user: "{{ forgejo_admin_user.username }}"
    api_password: "{{ forgejo_admin_user.password }}"

- name: enable ldap authentication
  when:
    - not running_in_check_mode
    - forgejo_auths.ldap is defined
    - forgejo_auths.ldap | count > 0
    - forgejo_auths.ldap.state is defined
    - forgejo_auths.ldap.state | string | length > 0
    - forgejo_auths.ldap.state is in ["present", "absent"]
  remote_user: "{{ forgejo_remote_user }}"
  become_user: "{{ forgejo_system_user }}"
  become: true
  bodsch.scm.forgejo_auth:
    name: "{{ forgejo_auths.ldap.name | default(omit) }}"
    state: "{{ forgejo_auths.ldap.state | default(omit) }}"
    active: "{{ forgejo_auths.ldap.active | default('true') | bool }}"
    security_protocol: "{{ forgejo_auths.ldap.security_protocol | default(omit) }}"
    skip_tls_verify: "{{ forgejo_auths.ldap.skip_tls_verify | default('true') | bool }}"
    hostname: "{{ forgejo_auths.ldap.hostname | default(omit) }}"
    port: "{{ forgejo_auths.ldap.port | default(omit) }}"
    user_search_base: "{{ forgejo_auths.ldap.user_search_base | default(omit) }}"
    filters:
      user: "{{ forgejo_auths.ldap.filters.user | default(omit) }}"
      admin: "{{ forgejo_auths.ldap.filters.admin | default(omit) }}"
      restricted: "{{ forgejo_auths.ldap.filters.restricted | default(omit) }}"
    allow_deactivate_all: "{{ forgejo_auths.ldap.allow_deactivate_all | default('false') | bool }}"
    attributes:
      username: "{{ forgejo_auths.ldap.attributes.username | default(omit) }}"
      firstname: "{{ forgejo_auths.ldap.attributes.firstname | default(omit) }}"
      surname: "{{ forgejo_auths.ldap.attributes.surname | default(omit) }}"
      email: "{{ forgejo_auths.ldap.attributes.email | default(omit) }}"
      public_ssh_key: "{{ forgejo_auths.ldap.attributes.public_ssh_key | default(omit) }}"
      avatar: "{{ forgejo_auths.ldap.attributes.avatar | default(omit) }}"
    skip_local_2fa: "{{ forgejo_auths.ldap.skip_local_2fa | default('false') | bool }}"
    bind_dn: "{{ forgejo_auths.ldap.bind_dn | default(omit) }}"
    bind_password: "{{ forgejo_auths.ldap.bind_password | default(omit) }}"
    attributes_in_bind: "{{ forgejo_auths.ldap.attributes_in_bind | default('false') | bool }}"
    synchronize_users: "{{ forgejo_auths.ldap.synchronize_users | default('false') | bool }}"
    config: "{{ forgejo_config_dir }}/forgejo.ini"
    working_dir: "{{ forgejo_working_dir }}"

...
