---

- name: detect our installation path '{{ forgejo_install_path | dirname }}'
  ansible.builtin.stat:
    path: "{{ forgejo_install_path | dirname }}"
    get_checksum: false
  register: stat_forgejo_path
  ignore_errors: true

- name: detect old installation
  ansible.builtin.stat:
    path: /usr/bin/forgejo
    get_checksum: false
  register: stat_old_forgejo_path
  ignore_errors: true

- name: detect if this an upgrade
  ansible.builtin.set_fact:
    forgejo_upgrade: "{{ stat_forgejo_path | bodsch.core.upgrade(stat_old_forgejo_path) }}"

- name: old installation
  when:
    - forgejo_upgrade
  block:
    - name: stop old service
      ansible.builtin.service:
        name: forgejo-server
        state: stopped
        enabled: false
      notify:
        - daemon-reload

    - name: uninstall old forgejo installation
      ansible.builtin.package:
        name: forgejo
        state: absent

    - name: remove installed systemd unit
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - /etc/systemd/system/forgejo-server.service
        - /usr/lib/systemd/system/forgejo-server.service

    - name: remove installed forgejo
      ansible.builtin.file:
        state: absent
        path: "{{ stat_forgejo_path.stat.path }}"
      when:
        - stat_forgejo_path.stat.path is defined
        - stat_forgejo_path.stat.path | string | length > 0

- name: flush handlers
  ansible.builtin.meta: flush_handlers

...
