---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: download
  ansible.builtin.include_tasks: download.yml

- name: external installation
  ansible.builtin.import_tasks: external_installation.yml

- name: install
  ansible.builtin.include_tasks: install.yml

- name: configure
  ansible.builtin.include_tasks: configure.yml

- name: authentications
  ansible.builtin.include_tasks: authentications.yml

- name: service
  ansible.builtin.include_tasks: service.yml

...
