---

- name: merge opengist configuration between defaults and custom
  ansible.builtin.set_fact:
    opengist_config: "{{ opengist_defaults_config | combine(opengist_config, recursive=True) }}"
    # opengist_tls_server: "{{ opengist_defaults_tls_server | combine(opengist_tls_server, recursive=True) }}"
    # opengist_http_server: "{{ opengist_defaults_http_server | combine(opengist_http_server, recursive=True) }}"
    # opengist_basic_auth_users: "{{ opengist_defaults_basic_auth_users | combine(opengist_basic_auth_users, recursive=True) }}"
    # opengist_collectors: "{{ opengist_defaults_collectors | combine(opengist_collectors, recursive=True) }}"

- name: create opengist configuration directory
  ansible.builtin.file:
    path: "{{ opengist_config_dir }}"
    state: directory
    owner: root
    group: "{{ opengist_user.group }}"
    mode: 0775

- name: create opengist configuration
  ansible.builtin.template:
    src: "opengist/config.yml.j2"
    dest: "{{ opengist_config_dir }}/config.yml"
    force: true
    owner: root
    group: "{{ opengist_user.group }}"
    mode: 0640
  notify:
    - restart opengist

...
