---

- name: user and group handling
  when:
    - not running_in_check_mode
    - opengist_user.owner != "root"
  block:
    - name: create opengist group
      ansible.builtin.group:
        name: "{{ opengist_user.group }}"
        state: present
        system: true

    - name: create opengist user
      ansible.builtin.user:
        comment: "Home Assistant"
        name: "{{ opengist_user.owner }}"
        groups: "{{ opengist_user.group }}"
        append: false
        home: "{{ opengist_user.home }}"
        shell: /sbin/nologin
        system: true
        createhome: true

    - name: create directory
      ansible.builtin.file:
        state: directory
        path: "{{ opengist_user.home }}"
        owner: "{{ opengist_user.owner }}"
        group: "{{ opengist_user.group }}"
        mode: "02775"

- name: add user {{ opengist_user.owner }} to groups
  when:
    - not running_in_check_mode
    - opengist_user.groups | default([]) | count > 0
  ansible.builtin.user:
    name: "{{ opengist_user.owner }}"
    groups: "{{ item }}"
    append: true
  loop:
    "{{ opengist_user.groups | sort | unique }}"

- name: create install directory
  when:
    - not running_in_check_mode
  ansible.builtin.file:
    path: "{{ opengist_install_path }}"
    state: directory
    owner: "{{ opengist_user.owner }}"
    group: "{{ opengist_user.group }}"
    mode: "0755"

- name: deploy and activate opengist version {{ opengist_version }}
  when:
    - not running_in_check_mode
  bodsch.core.deploy_and_activate:
    src_dir: "{{ opengist_local_tmp_directory }}"
    install_dir: "{{ opengist_install_path }}"
    link_dir: "/usr/bin"
    remote_src: "{{ ('true' if opengist_direct_download else 'false') | bool }}"
    owner: "{{ opengist_user.owner }}"
    group: "{{ opengist_user.group }}"
    mode: "0755"
    items:
      - name: "{{ opengist_release.binary }}"

- name: systemd
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
  block:
    - name: create opengist run configuration
      ansible.builtin.template:
        src: "default/opengist.j2"
        dest: "{{ opengist_defaults_directory }}/opengist"
        force: true
        owner: root
        group: "{{ opengist_user.group }}"
        mode: "0640"
      notify:
        - restart opengist

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/opengist.service.j2"
        dest: "{{ systemd_lib_directory }}/opengist.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - daemon-reload
        - restart opengist

- name: openrc
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/opengist.j2"
        dest: "/etc/conf.d/opengist"
        owner: root
        group: root
        mode: "0644"

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/opengist.j2"
        dest: "/etc/init.d/opengist"
        owner: root
        group: root
        mode: "0750"

- name: create custom fact file
  when:
    - not running_in_check_mode
  bodsch.core.facts:
    name: opengist
    facts:
      version: "{{ opengist_version }}"

...
