#!/usr/bin/env bash

# hooks/dispatch
set -euo pipefail

# . hooks/molecule.rc

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"   # absoluter Hook-Pfad
cmd=${0##*/}                                          # „converge“, „verify“, …

exec "$dir/run_tox.py" "$cmd" "$@"
