#!/usr/bin/env bash

. hooks/molecule.rc

set -x

if [ -z "${COLLECTION_DIR}" ]
then
  echo "missing collection directory"
  echo "run 'make install' first"

  exit 1
fi

if [ -d ${COLLECTION_DIR} ]
then
  # ansible-doc --list --list_files -t module ${COLLECTION_NAMESPACE}.${COLLECTION_NAME}

  ansible_modules=$(
    ansible-doc --list ${COLLECTION_NAMESPACE}.${COLLECTION_NAME} --json | jq -r 'keys[]'
  )

  for i in ${ansible_modules}
  do
    # echo " - ${i}"
    PAGER='cat' ansible-doc --type module ${i}
    echo ""
  done
fi

exit 0
