#!/usr/bin/env bash

. hooks/molecule.rc

if [ -z "${COLLECTION_DIR}" ]
then
  echo "missing collection directory"
  exit 0
fi

echo "remove ${COLLECTION_NAME} from ${COLLECTION_DIR}"

if [ -d ${COLLECTION_DIR} ]
then
  rm \
    --recursive \
    --force \
    "${COLLECTION_DIR}"
fi

exit 0
