---

- name: user and group handling
  when:
    - forgejo_runner_system_user != "root"
  block:
    - name: create forgejo-runner group
      ansible.builtin.group:
        name: "{{ forgejo_runner_system_group }}"
        state: present
        system: true

    - name: create forgejo-runner user
      ansible.builtin.user:
        name: "{{ forgejo_runner_system_user }}"
        groups: "{{ forgejo_runner_system_group }}"
        # append: true
        shell: /bin/bash
        system: true
        createhome: true
        home: "{{ forgejo_runner_working_dir }}"

- name: create install directory
  ansible.builtin.file:
    path: "{{ forgejo_runner_install_path }}"
    state: directory
    owner: "{{ forgejo_runner_system_user }}"
    group: "{{ forgejo_runner_system_group }}"
    mode: 0755

- name: detect binary file for forgejo-runner on '{{ forgejo_runner_delegate_to }}'
  become: false
  delegate_to: "{{ forgejo_runner_delegate_to }}"
  run_once: "{{ 'false' if forgejo_runner_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ forgejo_runner_local_tmp_directory }}/{{ forgejo_runner_release.binary }}"
  register: stat_file_binary

- name: fail when binary are missing
  ansible.builtin.fail:
    msg: "missing binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: detect installed forgejo-runner binary
  ansible.builtin.stat:
    path: "{{ forgejo_runner_install_path }}/forgejo-runner"
  register: stat_forgejo_runner_binary

- name: detect activated forgejo-runner binary
  ansible.builtin.stat:
    path: "/usr/bin/forgejo-runner"
  register: stat_forgejo_runner_activated

- name: install and activate forgejo
  when:
    - (stat_forgejo_runner_binary.stat is defined and not stat_forgejo_runner_binary.stat.exists | default('false')) or
      not stat_forgejo_runner_activated.stat | bodsch.core.linked_version(forgejo_runner_install_path, forgejo_runner_version)
  block:
    - name: propagate files
      block:
        - name: propagate forgejo-runner binary
          ansible.builtin.copy:
            src: "{{ forgejo_runner_local_tmp_directory }}/{{ forgejo_runner_release.binary }}"
            dest: "{{ forgejo_runner_install_path }}/forgejo-runner"
            mode: 0755
            owner: "{{ forgejo_runner_system_user }}"
            group: "{{ forgejo_runner_system_group }}"
            remote_src: "{{ 'true' if forgejo_runner_direct_download else 'false' }}"

        - name: make files executable
          ansible.builtin.file:
            path: "{{ forgejo_runner_install_path }}/forgejo-runner"
            mode: 0755
            owner: "{{ forgejo_runner_system_user }}"
            group: "{{ forgejo_runner_system_group }}"

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ forgejo_runner_install_path }}/forgejo-runner"
            dest: "/usr/bin/forgejo-runner"
            state: link
            force: true
            follow: false
          notify:
            - restart forgejo-runner

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ forgejo_runner_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create forgejo-runner run configuration
      ansible.builtin.template:
        src: "forgejo-runner.j2"
        dest: "{{ forgejo_runner_defaults_directory }}/forgejo-runner"
        force: true
        owner: root
        group: "{{ forgejo_runner_system_group }}"
        mode: 0640
      notify:
        - restart forgejo-runner

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/forgejo-runner.service.j2"
        dest: "{{ systemd_lib_directory }}/forgejo-runner.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart forgejo-runner

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/forgejo-runner.j2"
        dest: "/etc/conf.d/forgejo-runner"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/forgejo-runner.j2"
        dest: "/etc/init.d/forgejo-runner"
        owner: root
        group: root
        mode: 0750

- name: create custom fact file
  bodsch.core.facts:
    name: forgejo-runner
    facts:
      version: "{{ forgejo_runner_version }}"

...
