---

forgejo_version: 12.0.0

forgejo_system_user: forgejo
forgejo_remote_user: forgejo
forgejo_system_group: forgejo
forgejo_config_dir: /etc/forgejo
forgejo_working_dir: /var/lib/forgejo
forgejo_home_dir: /home/{{ forgejo_system_user }}

forgejo_systemd:
  unit:
    after:
      - syslog.target
      - network.target
    wants: []
    requires: []
  service:
    limits:
      nofile:
        soft: ""
        hard: ""

forgejo_release: {}

forgejo_direct_download: false

forgejo_name: "Forgejo - Beyond coding. We forge."
forgejo_app:
  display_name_format: !unsafe "{APP_NAME}: {APP_SLOGAN}"
  slogan: ""

# Either "dev", "prod" or "test", default is "prod"
forgejo_run_mode: "prod"

forgejo_admin_user:
  username: ""
  password: ""
  email: ""

forgejo_users: []
#   - username: ""
#     password: ""
#     email: ""
#     state:  absent / present

forgejo_actions: {}
forgejo_admin: {}
forgejo_api: {}
forgejo_attachment: {}
forgejo_auths:
  ldap: {}

forgejo_badges:
  # Enable repository badges (via shields.io or a similar generator)
  enabled: true
  # Template for the badge generator.
  generator_url_template: !unsafe "https://img.shields.io/badge/{{.label}}-{{.text}}-{{.color}}"

forgejo_cache: {}
forgejo_camo: {}
forgejo_cors: {}
forgejo_cron: {}
forgejo_database: {}
forgejo_email: {}
forgejo_f3: {}
forgejo_federation: {}
forgejo_git: {}
forgejo_highlight: {}
forgejo_i18n: {}
forgejo_indexer: {}
forgejo_lfs: {}
forgejo_log: {}

forgejo_mailer:
  enabled: ""                                     # false
  send_buffer_len: ""                             # 100
  subject_prefix: ""
  protocol: ""                                    # one of "smtp", "smtps", "smtp+starttls", "smtp+unix", "sendmail", "dummy"
  smtp_addr: ""
  smtp_port: ""                                   # 25:  insecure smtp / 465: smtp secure / 587: starttls
  enable_helo: ""                                 # true
  helo_hostname: ""
  force_trust_server_cert: ""                     # false
  use_client_cert: ""                             # false
  client_cert_file: ""                            # custom/mailer/cert.pem
  client_key_file: ""                             # custom/mailer/key.pem
  from: ""
  envelope_from: ""
  user: ""
  passwd: ""
  send_as_plain_text: ""                          # false
  sendmail_path: ""                               # sendmail
  sendmail_args: ""
  sendmail_timeout: ""                            # 5m
  sendmail_convert_crlf: ""                       # true
  from_display_name_format: ""                    # !unsafe "{{ .DisplayName }}" # Available Variables: `.DisplayName`, `.AppName` and `.Domain`.
  override_header:
    reply_to: []
    #   - test@example.com
    #   - test2@example.com
    content_type: []
    #   - text/html
    #   - charset=utf-8
    in_reply_to: []

forgejo_markdown: {}
forgejo_markup: {}
forgejo_metrics: {}
forgejo_migrations: {}
forgejo_mirror: {}
forgejo_oauth2: {}
forgejo_oauth2_client: {}
forgejo_openid: {}
forgejo_other: {}
forgejo_packages: {}
forgejo_picture: {}
forgejo_project: {}
forgejo_proxy: {}
forgejo_queue: {}
forgejo_repo_archive: {}
forgejo_repository: {}
forgejo_security: {}
forgejo_server: {}
forgejo_service: {}
forgejo_session: {}
forgejo_ssh: {}
forgejo_storage: {}
forgejo_task: {}
forgejo_time: {}
forgejo_ui: {}
forgejo_webhook: {}

...
