---

name: code linter

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'roles/repos/**'
      - 'plugins/modules/**'
      - 'plugins/module_utils/**'
      - 'molecule/repos_**'
      - '.ansible-lint'
      - '.yamllint'
      - '!.editorconfig'
      - '!Makefile'
      - '!hooks/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'roles/repos/**'
      - 'plugins/modules/**'
      - 'plugins/module_utils/**'
      - 'molecule/repos_**'
      - '.ansible-lint'
      - '.yamllint'

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r test-requirements.txt

      - name: Lint code.
        run: |
          yamllint .
          flake8 plugins/

...
